name: CI

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        ruby:
        - "3.1"
        - "3.0"
        - debug

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - run: bundle install

      - run: rake spec

      - run: rake build

      - run: gem install pkg/*.gem
        if: matrix.ruby != 'debug'
